version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8000"  # Порт для HTTP трафика
      - "--entrypoints.metrics.address=:8899"  # Порт для метрик
      - "--metrics.prometheus=true"  # Включаем поддержку метрик Prometheus
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--metrics.prometheus.entrypoint=metrics"

    ports:
      - "8000:8000"
      - "8080:8080"
      - "8899:8899"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - fastapi_network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`localhost`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://crud_user:crud_user@db/characters_api"
    networks:
      - fastapi_network
    command: >
      bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: crud_user
      POSTGRES_PASSWORD: crud_user
      POSTGRES_DB: characters_api
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fastapi_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    networks:
      - fastapi_network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  db_data:

networks:
  fastapi_network:
    driver: bridge
